"""
ASS Style Builder — Generates ASS file headers, styles, and dialogue lines.
Handles color conversion (RGB→BGR), style definitions, and safe-zone positioning.
"""

import sys
from pathlib import Path
from typing import List, Dict, Any, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config


class ASSStyleBuilder:
    """
    Builds ASS subtitle file components: Script Info header, V4+ Styles,
    and Dialogue event lines. Configured for 1080x1920 portrait reels.
    """

    def __init__(
        self,
        font_name: str = "Noto Sans Gujarati",
        font_size: int = 72,
        base_color: str = "#FFFFFF",
        highlight_color: str = "#FFCC00",
        glow_color: str = "#FFD700",
        outline_width: int = 5,
        shadow: int = 3,
        margin_v: int = 460,
        enable_pill_bg: bool = False,
    ):
        self.font_name = font_name
        self.font_size = font_size
        self.base_color = base_color
        self.highlight_color = highlight_color
        self.glow_color = glow_color
        self.outline_width = outline_width
        self.shadow = shadow
        self.margin_v = margin_v
        self.enable_pill_bg = enable_pill_bg

        # Pre-compute ASS colors (BGR format)
        self.base_ass = self.rgb_to_ass_color(base_color)
        self.highlight_ass = self.rgb_to_ass_color(highlight_color)
        self.glow_ass = self.rgb_to_ass_color(glow_color) if glow_color else self.highlight_ass
        self.back_ass = "&H80000000" if enable_pill_bg else "&H00000000"
        self.border_style = 3 if enable_pill_bg else 1

    @staticmethod
    def rgb_to_ass_color(hex_rgb: str, alpha: int = 0x00) -> str:
        """
        Convert '#RRGGBB' hex string to ASS color format '&HAABBGGRR'.
        ASS uses BGR byte order, not RGB.
        """
        cleaned = hex_rgb.lstrip("#")
        if len(cleaned) != 6:
            return "&H00FFFFFF"
        r, g, b = cleaned[0:2], cleaned[2:4], cleaned[4:6]
        return f"&H{alpha:02X}{b}{g}{r}"

    @staticmethod
    def format_ass_time(seconds: float) -> str:
        """Convert float seconds to ASS timestamp format: H:MM:SS.cc"""
        seconds = max(0.0, seconds)
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = int(seconds % 60)
        centis = int(round((seconds - int(seconds)) * 100))
        if centis >= 100:
            secs += 1
            centis = 0
        return f"{hours}:{minutes:02d}:{secs:02d}.{centis:02d}"

    def build_header(self) -> str:
        """
        Build the complete ASS file header with Script Info and V4+ Styles.
        Configured for 1080x1920 Instagram Reel safe zones.
        """
        outline_color = "&H00000000"  # Black outline

        header = f"""[Script Info]
; Generated by Prarambh Advanced Subtitle Engine
ScriptType: v4.00+
PlayResX: {config.VIDEO_WIDTH}
PlayResY: {config.VIDEO_HEIGHT}
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Prarambh,{self.font_name},{self.font_size},{self.base_ass},{self.highlight_ass},{outline_color},{self.back_ass},-1,0,0,0,100,100,0,0,{self.border_style},{self.outline_width},{self.shadow},2,80,80,{self.margin_v},1
Style: PrarambhHighlight,{self.font_name},{self.font_size},{self.highlight_ass},{self.highlight_ass},{outline_color},{self.back_ass},-1,0,0,0,100,100,0,0,{self.border_style},{self.outline_width},{self.shadow},2,80,80,{self.margin_v},1
Style: PrarambhGlow,{self.font_name},{self.font_size},{self.highlight_ass},{self.highlight_ass},{self.glow_ass},{self.back_ass},-1,0,0,0,100,100,0,0,{self.border_style},{self.outline_width + 1},0,2,80,80,{self.margin_v},1
"""
        return header

    def build_dialogue_line(
        self,
        start_time: float,
        end_time: float,
        text: str,
        style: str = "Prarambh",
        layer: int = 0,
    ) -> str:
        """Build a single ASS Dialogue: line."""
        start_str = self.format_ass_time(start_time)
        end_str = self.format_ass_time(end_time)
        return f"Dialogue: {layer},{start_str},{end_str},{style},,0,0,0,,{text}"

    def build_events_section(self, dialogue_lines: List[str]) -> str:
        """Build the complete [Events] section with format header and all dialogue lines."""
        events = "\n[Events]\n"
        events += "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
        for line in dialogue_lines:
            events += line + "\n"
        return events

    def build_full_ass(self, dialogue_lines: List[str]) -> str:
        """Build the complete ASS file content (header + events)."""
        return self.build_header() + self.build_events_section(dialogue_lines)
