"""
ASS Multi-Language Builder
==========================
Generates ASS subtitle file header and events with dual Latin & Gujarati style
definitions and inline font switching tags for 1080x1920 portrait reels.
"""

import sys
from pathlib import Path
from typing import List, Dict, Any, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config
from core.subtitle_presets import get_subtitle_preset
from core.word_styler import WordStyler


class ASSMultiLangBuilder:
    """
    Constructs complete ASS subtitle script files configured with
    dual font styles, safe-zone positioning, and word animations.
    """

    def __init__(
        self,
        preset: Optional[Dict[str, Any]] = None,
        style_preset: Optional[str] = None,
    ):
        if preset is not None and isinstance(preset, dict):
            self.preset = preset
        elif style_preset:
            self.preset = get_subtitle_preset(style_preset)
        elif isinstance(preset, str):
            self.preset = get_subtitle_preset(preset)
        else:
            self.preset = get_subtitle_preset("mixed_highlight")

        self.styler = WordStyler(self.preset)


    @staticmethod
    def format_ass_time(seconds: float) -> str:
        """Convert float seconds to ASS timestamp: H:MM:SS.cc"""
        seconds = max(0.0, seconds)
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = int(seconds % 60)
        centis = int(round((seconds - int(seconds)) * 100))
        if centis >= 100:
            secs += 1
            centis = 0
        return f"{hours}:{minutes:02d}:{secs:02d}.{centis:02d}"

    def build_header(self) -> str:
        """
        Builds the ASS [Script Info] and [V4+ Styles] section.
        """
        base_font = self.preset.get("base_font", "Noto Sans Gujarati")
        base_size = self.preset.get("base_size", 72)
        base_color = WordStyler.rgb_to_ass_bgr(
            self.preset.get("base_color", "#FFFFFF"),
            alpha=self.preset.get("base_alpha", 0x00)
        )
        base_outline = WordStyler.rgb_to_ass_bgr(self.preset.get("base_outline", "#000000"))
        outline_w = self.preset.get("base_outline_width", 5)
        shadow_w = self.preset.get("base_shadow", 3)
        margin_v = self.preset.get("margin_v", 460)

        latin_font = self.preset.get("latin_font", "Anton")
        latin_color = WordStyler.rgb_to_ass_bgr(self.preset.get("latin_color", "#FFD700"))

        # Pill background config
        enable_pill = self.preset.get("pill_bg", False)
        border_style = 3 if enable_pill else 1
        pill_opacity = int((1.0 - self.preset.get("pill_opacity", 0.65)) * 255) if enable_pill else 0x00
        pill_col = WordStyler.rgb_to_ass_bgr(self.preset.get("pill_color", "#000000"), alpha=pill_opacity)

        header = f"""[Script Info]
; Generated by Prarambh Multi-Language Subtitle Engine
ScriptType: v4.00+
PlayResX: {config.VIDEO_WIDTH}
PlayResY: {config.VIDEO_HEIGHT}
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: PrarambhBase,{base_font},{base_size},{base_color},{latin_color},{base_outline},{pill_col},-1,0,0,0,100,100,0,0,{border_style},{outline_w},{shadow_w},2,80,80,{margin_v},1
Style: PrarambhLatin,{latin_font},{int(base_size * self.preset.get("latin_scale", 1.10))},{latin_color},{latin_color},{base_outline},{pill_col},-1,0,0,0,100,100,0,0,{border_style},{outline_w},{shadow_w},2,80,80,{margin_v},1
"""
        return header

    def build_dialogue_line(
        self,
        start_sec: float,
        end_sec: float,
        text: str,
        style: str = "PrarambhBase",
        layer: int = 0,
    ) -> str:
        """Formats a single Dialogue line with timestamps and style."""
        s_str = self.format_ass_time(start_sec)
        e_str = self.format_ass_time(end_sec)
        return f"Dialogue: {layer},{s_str},{e_str},{style},,0,0,0,,{text}"

    def build_events(self, chunks: List[List[Dict[str, Any]]]) -> str:
        """
        Builds the complete [Events] section from a list of word chunks.
        """
        lines = ["[Events]", "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"]

        for idx, chunk in enumerate(chunks):
            if not chunk:
                continue
            start_sec = chunk[0]["start"]
            end_sec = chunk[-1]["end"]

            styled_text = self.styler.style_chunk(chunk, chunk_index=idx, enable_animation=True)
            line = self.build_dialogue_line(start_sec, end_sec, styled_text, style="PrarambhBase")
            lines.append(line)

        return "\n".join(lines) + "\n"

    def build_full_ass(self, chunks: List[List[Dict[str, Any]]]) -> str:
        """Combines Header + Events into full ASS script string."""
        return self.build_header() + "\n" + self.build_events(chunks)

    def build_ass(self, chunks: List[List[Dict[str, Any]]]) -> str:
        """Alias for build_full_ass."""
        return self.build_full_ass(chunks)

