"""
Subtitle Style Presets — 20 Viral Presets for Prarambh Reel Studio
==================================================================
Comprehensive style definitions including the flagship bilingual preset
(White Gujarati Noto Sans + Yellow Anton Latin display font),
Hormozi, CapCut, Neon, Festive Gujarati, News Anchor, and more.
"""

from typing import Dict, Any, List, Optional


SUBTITLE_PRESETS_20: Dict[str, Dict[str, Any]] = {
    # ── 1. Mixed Language Highlight (Flagship Reference Style) ─────────────────
    "mixed_highlight": {
        "id": "mixed_highlight",
        "name": "Mixed Language Highlight",
        "category": "bilingual",
        "icon": "🎯",
        "description": "Gujarati white + English yellow Anton. The viral bilingual style.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 72,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FFD700",
        "latin_scale": 1.10,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 3,
        "animation": "bounce_soft",
        "glow": False,
        "glow_color": None,
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 2. Hormozi Classic ───────────────────────────────────────────────────
    "hormozi_classic": {
        "id": "hormozi_classic",
        "name": "Hormozi Classic",
        "category": "bold",
        "icon": "💥",
        "description": "Big bold white text, yellow word highlight with glow. Alex Hormozi style.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 76,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 6,
        "base_shadow": 4,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FFCC00",
        "latin_scale": 1.15,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": True,
        "chunk_size": 2,
        "animation": "bounce_hard",
        "glow": True,
        "glow_color": "#FFD700",
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 3. CapCut Default ────────────────────────────────────────────────────
    "capcut_default": {
        "id": "capcut_default",
        "name": "CapCut Default",
        "category": "minimal",
        "icon": "✨",
        "description": "Clean white text on dark rounded pill, cyan highlight, 3-word chunks.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 64,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 3,
        "base_shadow": 2,
        "base_alpha": 0x00,
        "latin_font": "Montserrat",
        "latin_color": "#00E5FF",
        "latin_scale": 1.05,
        "latin_uppercase": False,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 3,
        "animation": "pop",
        "glow": False,
        "glow_color": None,
        "pill_bg": True,
        "pill_color": "#000000",
        "pill_opacity": 0.65,
        "margin_v": 460,
    },

    # ── 4. Neon Cyber ────────────────────────────────────────────────────────
    "neon_cyber": {
        "id": "neon_cyber",
        "name": "Neon Cyber",
        "category": "cyber",
        "icon": "💜",
        "description": "Magenta neon glow with cyan outlines. High-energy cyberpunk aesthetic.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 70,
        "base_color": "#FFFFFF",
        "base_outline": "#FF00FF",
        "base_outline_width": 4,
        "base_shadow": 0,
        "base_alpha": 0x00,
        "latin_font": "Bebas Neue",
        "latin_color": "#00FFFF",
        "latin_scale": 1.12,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": True,
        "chunk_size": 2,
        "animation": "glitch",
        "glow": True,
        "glow_color": "#FF00FF",
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 5. Gujarati Pride ────────────────────────────────────────────────────
    "gujarati_pride": {
        "id": "gujarati_pride",
        "name": "Gujarati Pride",
        "category": "bilingual",
        "icon": "🦁",
        "description": "Bold saffron orange Gujarati words with crisp white English highlights.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 74,
        "base_color": "#FF6600",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FFFFFF",
        "latin_scale": 1.05,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 3,
        "animation": "bounce_soft",
        "glow": False,
        "glow_color": None,
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 6. News Anchor ───────────────────────────────────────────────────────
    "news_anchor": {
        "id": "news_anchor",
        "name": "News Anchor",
        "category": "news",
        "icon": "📺",
        "description": "Broadcast news lower-third ticker with solid red backdrop and gold text.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 60,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 3,
        "base_shadow": 2,
        "base_alpha": 0x00,
        "latin_font": "Montserrat",
        "latin_color": "#FFCC00",
        "latin_scale": 1.0,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 4,
        "animation": "slide_up",
        "glow": False,
        "glow_color": None,
        "pill_bg": True,
        "pill_color": "#C8102E",
        "pill_opacity": 0.88,
        "margin_v": 440,
    },

    # ── 7. Karaoke Fill ──────────────────────────────────────────────────────
    "karaoke_fill": {
        "id": "karaoke_fill",
        "name": "Karaoke Fill",
        "category": "bold",
        "icon": "🎤",
        "description": "Whole phrase renders in white; active spoken word fills with gold.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 70,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FFD700",
        "latin_scale": 1.05,
        "latin_uppercase": False,
        "latin_bold": True,
        "latin_glow": True,
        "chunk_size": 4,
        "animation": "karaoke_fill",
        "glow": True,
        "glow_color": "#FFD700",
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 8. Typewriter ────────────────────────────────────────────────────────
    "typewriter": {
        "id": "typewriter",
        "name": "Typewriter",
        "category": "minimal",
        "icon": "⌨️",
        "description": "Terminal style rapid letter reveal with bright neon green cursor.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 64,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 4,
        "base_shadow": 2,
        "base_alpha": 0x00,
        "latin_font": "Poppins",
        "latin_color": "#00FF66",
        "latin_scale": 1.0,
        "latin_uppercase": False,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 2,
        "animation": "typewriter",
        "glow": False,
        "glow_color": None,
        "pill_bg": True,
        "pill_color": "#111827",
        "pill_opacity": 0.75,
        "margin_v": 460,
    },

    # ── 9. Word Stack ────────────────────────────────────────────────────────
    "word_stack": {
        "id": "word_stack",
        "name": "Word Stack",
        "category": "bold",
        "icon": "🥞",
        "description": "Single punchy word bursts in oversized typography for maximum impact.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 80,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 6,
        "base_shadow": 4,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FF3366",
        "latin_scale": 1.20,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 1,
        "animation": "pop",
        "glow": False,
        "glow_color": None,
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 10. Gradient Pop ─────────────────────────────────────────────────────
    "gradient_pop": {
        "id": "gradient_pop",
        "name": "Gradient Pop",
        "category": "cyber",
        "icon": "🌸",
        "description": "Words pop in with vivid ultraviolet and neon pink highlights.",
        "base_font": "Poppins",
        "base_size": 68,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Poppins",
        "latin_color": "#FF6EC7",
        "latin_scale": 1.10,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": True,
        "chunk_size": 2,
        "animation": "pop",
        "glow": True,
        "glow_color": "#EC4899",
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 11. Outline Only ─────────────────────────────────────────────────────
    "outline_only": {
        "id": "outline_only",
        "name": "Outline Only",
        "category": "minimal",
        "icon": "⭕",
        "description": "Hollow transparent text with thick high-contrast white & gold stroke.",
        "base_font": "Anton",
        "base_size": 78,
        "base_color": "#000000",
        "base_outline": "#FFFFFF",
        "base_outline_width": 7,
        "base_shadow": 2,
        "base_alpha": 0xCC,
        "latin_font": "Anton",
        "latin_color": "#000000",
        "latin_scale": 1.10,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 2,
        "animation": "bounce_soft",
        "glow": False,
        "glow_color": None,
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 12. Two-Line Split ───────────────────────────────────────────────────
    "two_line_split": {
        "id": "two_line_split",
        "name": "Two-Line Split",
        "category": "bilingual",
        "icon": "⏸️",
        "description": "Gujarati on line 1, English key phrases on line 2 for clean readability.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 68,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FFD700",
        "latin_scale": 1.12,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 4,
        "animation": "slide_up",
        "glow": False,
        "glow_color": None,
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 13. Emoji Enhanced ───────────────────────────────────────────────────
    "emoji_enhanced": {
        "id": "emoji_enhanced",
        "name": "Emoji Enhanced",
        "category": "festive",
        "icon": "⚡",
        "description": "Adds energetic visual flair and emoji highlights to power words.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 68,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FFD700",
        "latin_scale": 1.10,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 3,
        "animation": "bounce_soft",
        "glow": False,
        "glow_color": None,
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 14. Boxed Words ──────────────────────────────────────────────────────
    "boxed_words": {
        "id": "boxed_words",
        "name": "Boxed Words",
        "category": "minimal",
        "icon": "📦",
        "description": "Structured high-contrast box pill container with yellow highlights.",
        "base_font": "Poppins",
        "base_size": 62,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 3,
        "base_shadow": 2,
        "base_alpha": 0x00,
        "latin_font": "Poppins",
        "latin_color": "#FFD700",
        "latin_scale": 1.05,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 3,
        "animation": "pop",
        "glow": False,
        "glow_color": None,
        "pill_bg": True,
        "pill_color": "#000000",
        "pill_opacity": 0.70,
        "margin_v": 460,
    },

    # ── 15. Rainbow Wave ─────────────────────────────────────────────────────
    "rainbow_wave": {
        "id": "rainbow_wave",
        "name": "Rainbow Wave",
        "category": "festive",
        "icon": "🌈",
        "description": "Multi-colored animated spectrum sequence for celebratory content.",
        "base_font": "Anton",
        "base_size": 72,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#00E5FF",
        "latin_scale": 1.10,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": True,
        "chunk_size": 3,
        "animation": "wave_bounce",
        "glow": True,
        "glow_color": "#00E5FF",
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 16. Shadow Depth ─────────────────────────────────────────────────────
    "shadow_depth": {
        "id": "shadow_depth",
        "name": "Shadow Depth",
        "category": "bold",
        "icon": "🗿",
        "description": "Extruded 3D drop shadow providing massive depth and legibility.",
        "base_font": "Anton",
        "base_size": 74,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 3,
        "base_shadow": 7,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FFD700",
        "latin_scale": 1.12,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 2,
        "animation": "bounce_hard",
        "glow": False,
        "glow_color": None,
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 17. Glow Pulse ───────────────────────────────────────────────────────
    "glow_pulse": {
        "id": "glow_pulse",
        "name": "Glow Pulse",
        "category": "cyber",
        "icon": "💡",
        "description": "Soft atmospheric cyan glow that breathes rhythmically with narration.",
        "base_font": "Poppins",
        "base_size": 68,
        "base_color": "#FFFFFF",
        "base_outline": "#00E5FF",
        "base_outline_width": 4,
        "base_shadow": 0,
        "base_alpha": 0x00,
        "latin_font": "Poppins",
        "latin_color": "#00E5FF",
        "latin_scale": 1.08,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": True,
        "chunk_size": 2,
        "animation": "pulse",
        "glow": True,
        "glow_color": "#00E5FF",
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 18. Bounce Wave ──────────────────────────────────────────────────────
    "bounce_wave": {
        "id": "bounce_wave",
        "name": "Bounce Wave",
        "category": "bold",
        "icon": "🌊",
        "description": "Rhythmic wave overshoot bounce with emerald green English accents.",
        "base_font": "Anton",
        "base_size": 72,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#00FF7F",
        "latin_scale": 1.15,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": False,
        "chunk_size": 3,
        "animation": "wave_bounce",
        "glow": False,
        "glow_color": None,
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 19. Shake Emphasis ───────────────────────────────────────────────────
    "shake_emphasis": {
        "id": "shake_emphasis",
        "name": "Shake Emphasis",
        "category": "news",
        "icon": "🚨",
        "description": "Urgent breaking news style with red keywords and rapid alert vibration.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 72,
        "base_color": "#FFFFFF",
        "base_outline": "#000000",
        "base_outline_width": 5,
        "base_shadow": 3,
        "base_alpha": 0x00,
        "latin_font": "Anton",
        "latin_color": "#FF1744",
        "latin_scale": 1.18,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": True,
        "chunk_size": 2,
        "animation": "bounce_hard",
        "glow": True,
        "glow_color": "#FF1744",
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },

    # ── 20. Festive Gujarati ─────────────────────────────────────────────────
    "festive_gujarati": {
        "id": "festive_gujarati",
        "name": "Festive Gujarati",
        "category": "festive",
        "icon": "🪔",
        "description": "Marigold gold & royal crimson festive tones for Navratri, Diwali, and Utsavs.",
        "base_font": "Noto Sans Gujarati",
        "base_size": 74,
        "base_color": "#FFD700",
        "base_outline": "#8B0000",
        "base_outline_width": 6,
        "base_shadow": 4,
        "base_alpha": 0x00,
        "latin_font": "Poppins",
        "latin_color": "#FFFFFF",
        "latin_scale": 1.10,
        "latin_uppercase": True,
        "latin_bold": True,
        "latin_glow": True,
        "chunk_size": 3,
        "animation": "pop",
        "glow": True,
        "glow_color": "#FFD700",
        "pill_bg": False,
        "pill_color": "#000000",
        "pill_opacity": 0.0,
        "margin_v": 460,
    },
}

# Populate backward compatibility alias fields
for _p in SUBTITLE_PRESETS_20.values():
    _p.setdefault("highlight_color", _p.get("latin_color", "#FFD700"))
    _p.setdefault("font_size", _p.get("base_size", 72))
    _p.setdefault("font_name", _p.get("base_font", "Noto Sans Gujarati"))


def get_subtitle_preset(preset_id: str) -> Dict[str, Any]:

    """Retrieves a preset dictionary by ID, defaulting to 'mixed_highlight'."""
    return SUBTITLE_PRESETS_20.get(preset_id, SUBTITLE_PRESETS_20["mixed_highlight"]).copy()


def list_subtitle_presets(category: Optional[str] = None) -> List[Dict[str, Any]]:
    """Returns list of presets, optionally filtered by category."""
    presets = list(SUBTITLE_PRESETS_20.values())
    if category and category != "all":
        presets = [p for p in presets if p.get("category") == category]
    return presets


def get_preset_categories() -> List[Dict[str, str]]:
    """Returns all available preset categories for UI filters."""
    return [
        {"id": "all", "label": "All Styles", "icon": "🌟"},
        {"id": "bilingual", "label": "Bilingual (Guj + Eng)", "icon": "🎯"},
        {"id": "bold", "label": "Bold & Viral", "icon": "💥"},
        {"id": "minimal", "label": "Clean & Minimal", "icon": "✨"},
        {"id": "cyber", "label": "Neon & Cyber", "icon": "💜"},
        {"id": "news", "label": "News Ticker", "icon": "📺"},
        {"id": "festive", "label": "Festive Gujarati", "icon": "🪔"},
        {"id": "cinematic", "label": "Cinematic & Drama", "icon": "🎬"},
        {"id": "creative", "label": "Creative & Fun", "icon": "🎨"},
    ]

